### ISSUE TITLE
What is the license policy of npm logo?

### ISSUE THREAD

**Issue by kosamari** [npm/logos#5]
Per my friend's request, I'd like to make a scarf with npm logo as motif pattern. 
https://twitter.com/LewisCowper/status/688176143904591872

What is license policy for personal / not for profit use of npm logo?
Also, do you have any white space / background color guideline for logo use?

**Comment by ashleygwilliams** [comment]
hey @kosamari- pinging @cowperthwait and @kaseybyrne. they'll know for sure

generally though 😍😍

**Comment by cowperthwait** [comment]
hi @kosamari:
1. OMG OMG OMG OMG.
2. The license policy is here: [The npm trademark policy](https://www.npmjs.com/policies/trademark#the-npm-trademark-policy). As best I can tell, a personal, not for profit, display of the npm logo on a scarf would fall under the following bits:

> The primary purpose of your project is to promote the spread and improvement of the npm client software or the npm registry service.
> Your project is non-commercial in nature (it can make money to cover its costs or contribute to non-profit entities, but it cannot be run as a for-profit project or business).
> Your project neither promotes nor is associated with entities that currently fail to comply with the Artistic License 2.0 under which npm is distributed, or which are in violation of this trademark policy.

Consequently, the scarf seems totally legit. As a personal request (not a requirement), we would go gaga to get a photo of the finished work, because, [see no. 1].

> Also, do you have any white space / background color guideline for logo use?

Yes. I’ve attached to this comment. But obviously these are more relevant to our use in business/press contexts. I don’t think we had scarves in mind. :)

<img width="1010" alt="zl9d" src="https://cloud.githubusercontent.com/assets/13108914/12375225/67873d7c-bc6d-11e5-968a-36a5cb17aeea.png">
